Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?serverTimezone=Europe/Moscow&useSSL=false
    username: root
    password: root
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    rest:
      base-path: /datarest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
logging:
  file:
    name: logfile.txt
