Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/holyvacation?serverTimezone=Europe/Moscow&useSSL=false
    username: root
    password: root
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.mail.ru
    username: holyvacationtest@mail.ru
    password: otusspring123
    protocol: smtps
    port: 465
jwt:
  token:
    secret: jwtsecret
    expired: 3600000
notification:
  days-left: 5